# Generated by Django 4.2.11 on 2026-03-09 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='challenger',
            field=models.ForeignKey(help_text='Participant A — the one issuing the challenge.', on_delete=django.db.models.deletion.CASCADE, related_name='challenged_bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='creator',
            field=models.ForeignKey(help_text='The user who created this bet record (may be an admin acting on behalf).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Deadline to resolve the bet.', null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='When the bet event takes place.', null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='opponent',
            field=models.ForeignKey(help_text='Participant B — the one being challenged.', on_delete=django.db.models.deletion.CASCADE, related_name='opponent_bets', to=settings.AUTH_USER_MODEL),
        ),
    ]
