# Generated by Django 4.2.11 on 2026-03-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_bet_challenger_alter_bet_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='amount',
        ),
        migrations.AddField(
            model_name='bet',
            name='challenger_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What the challenger stands to win (paid by opponent if challenger wins).', max_digits=12),
        ),
        migrations.AddField(
            model_name='bet',
            name='opponent_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What the opponent stands to win (paid by challenger if opponent wins).', max_digits=12),
        ),
    ]
