# Generated by Django 4.2.11 on 2026-03-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_bet_proposal_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='event_date',
        ),
    ]
