# Generated by Django 4.2.11 on 2026-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_remove_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='due_date',
            field=models.DateField(blank=True, help_text='Deadline to resolve the bet.', null=True),
        ),
    ]
