# Generated by Django 4.2.11 on 2026-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, help_text='8-character code used to join this group.', max_length=8, unique=True),
        ),
    ]
